### ISSUE TITLE
Travis kills the build when the log file has more than 10000 lines

### ISSUE THREAD

**Issue by th-otto** [freemint/freemint#101]
Ok, googled a bit about this, and i think found a solution: redirect everything to a log file, and in case of a failed build (the after_success hook can be used for it), do a tail -9000 logfile (and hope the error causing the failure appears in the last lines). Only problem: travis thinks that your build has stalled when there is no console output for 10min. To prevent this, add something like
```
while sleep 5m; do echo "=====[ $SECONDS seconds, still building... ]====="; done &
```
to the build script, before actually starting make, and kill that job when done.

Still not perfect, because you can't follow the log anymore while it is still building (which i sometimes do when testing new environments/features).

**Comment by mikrosk** [comment]
Oh crap. Yes, m68k-atari-mint-gcc build suffers from the same problem. I'd be tempted to kill the number of CPU targets & remove OLD_BUILD more than ever but we still need a test of generic `make` to pass so in short-term reducing the number of CPU targets would help, we could get into trouble sooner or later anyway.

**Comment by mikrosk** [comment]
As mentioned in #97, I have found an elegant cure to this. Hopefully I'll manage to do it soon.

**Comment by mikrosk** [comment]
Should be (forever) fixed by https://github.com/freemint/freemint/commit/36cf2b41b10394e42ce50ccb0035afbc81a851b7.

**Comment by th-otto** [comment]
Nice one. So every target is now a separate job in Travis?

**Comment by mikrosk** [comment]
Yeah, it takes about two three minutes per build. I think there is enough reserve for future additions. ;)

**Comment by mfro0** [comment]
I'm reopening this. Not because of any Travis problem, but because I think build logs become difficult to follow, as huge as they are.

I'd like to discuss if anybody would object silencing the build logs to only spit out errors (similar to what e.g. a Linux kernel build does)?

Here is an example on what Linux build logs look like:
```
CHK     include/generated/compile.h
UPD     include/generated/compile.h
CC      init/version.o
CC      init/do_mounts.o
CC      init/do_mounts_initrd.o
LD      init/mounts.o
CC      init/initramfs.o
CC      init/calibrate.o
CC      init/init_task.o
LD      init/built-in.o

```

(compiler warnings and errors still show up, of course, it's just in this example, I didn't have any)

If nobody objects, I'd probably start working on something similar.

**Comment by th-otto** [comment]
I would prefer to leave them as is. Normally, you don't have to look at the logs, unless some problem appears. And in that case it is helpful to see the complete command line.

And for travis sake, that does not make any difference, in both cases they just count as one line.

**Comment by mikrosk** [comment]
Especially with the multi-CPU builds it is helpful to double check that the right switch has been used, @th-otto spotted a few errors like that in the past.

**Comment by mfro0** [comment]
Agreed that it is sometimes helpful to see everyhing. I'd provide an option to restore "chatty" behaviour if required (just as the Linux kernel build does):

```
VERBOSE=1 make
```

I wouldn't care much about Travis build defaults (i.e. they can be as "chatty" as wanted as far as I'm concerned). It's just when I do builds at home (with lots of multiple threads now possible thanks to Makefile improvements) I often find myself scrolling back several pages to get to the root cause which is annoying.

**Comment by th-otto** [comment]
Yes, for own builds that might make sense. But that might require changes to lots of Makefiles, to pass that setting down to sub-makes.

As for parallel makes, there still seems to be a problem sometimes. But it is hard to reproduce, since it depends how long the individual passes take.

**Comment by mikrosk** [comment]
@th-otto (IIRC) has done it in mintlib already: https://github.com/freemint/mintlib/blob/master/configvars#L18
