### ISSUE TITLE
tosdelay.c should use SuperToUser

### ISSUE THREAD

**Issue by czietz** [freemint/freemint#139]
Instead of switching back to user mode like so...
https://github.com/freemint/freemint/blob/60093b4668a9603f1e3cd78d4b0b411d58a7d025/sys/usb/src.km/tosdelay.c#L106
... tosdelay.c should use the _safe_ way provided specifically for that by osbind.h:
https://github.com/freemint/mintlib/blob/master/include/mint/osbind.h#L1015-L1042

**Comment by vinriviere** [comment]
For memories, I introduced `SuperToUser()` because the standard way was definitely **no safe** on plain TOS/EmuTOS. This is because on such OS, the value of the stack pointer is slightly changed by the trap implementation when returning to user mode, while it shouldn't. As GCC assumes that the stack pointer is not changed, it has awful consequences. I hit that issue again and again on plain TOS. On the other hand, `SuperToUser()` manually handles the stack, so it is always safe.

IIRC, it seemed that such `Super()` stack issue was fixed in FreeMiNT. As the USB driver can only run on FreeMiNT, it should never hit the Super() problem. But anyway, calling `SuperToUser()` in all cases will not hurt.

**Comment by th-otto** [comment]
On Sonntag, 19. Januar 2020 23:09:29 CET Vincent Rivière wrote:
> it seemed that such `Super()` stack issue was fixed in FreeMiNT. As the USB
> driver can only run on FreeMiNT, it should never hit the Super() problem.

IIRC, the problem is independent on how Super() is implemented. It is caused 
by the fact that gcc does not always adjusts the stack after every function 
call, but sometimes "accumulates" them. So if you do something like

sp = Super(0);
func1(1l, 2l, 3l);
Super(sp);
func2(1l, 2l, 3l);

instead adjusting the sp by 12 bytes after each call to func1() and func2(), 
it may adjust it only by 24 at the end. However, at that time it was already 
modified back by the 2nd Super call, and you end up with a sp that is 12 bytes 
to high.

**Comment by czietz** [comment]
> IIRC, it seemed that such `Super()` stack issue was fixed in FreeMiNT. As the USB driver can only run on FreeMiNT, it should never hit the Super() problem. 

No, the USB drivers can run under TOS and EmuTOS, too. In fact, the code in `tosdelay.c` is _only_ used in the TOS versions of the driver. Therefore, not using SuperToUser is unsafe.

**Comment by DavidGZ** [comment]
Thanks for pointing this out, I'll fix it.

I found another one here:

https://github.com/freemint/freemint/blob/60093b4668a9603f1e3cd78d4b0b411d58a7d025/sys/usb/src.km/udd/storage/usb_scsidrv.c#L55

That one probably it's still present in the Lightning drivers too

**Comment by DavidGZ** [comment]
Fixed with 6d49223027e0d3e92509b1886656bae810c9bb98

**Comment by vinriviere** [comment]
> IIRC, the problem is independent on how Super() is implemented. It is caused by the fact that gcc does not always adjusts the stack after every function call, but sometimes "accumulates" them.

The problem becomes **visible** when GCC does that. But it is always present due to bad `Super()` implementation in TOS. It may be partially hidden when compiling user programs without `-fomit-frame-pointer` as the stack is saved and restored inside each function.

**Comment by mikrosk** [comment]
Interestingly, I have never considered this a problem - the only time I bumped into this was when I called Super(0L) in main() and then Super(old_ssp) in some exit function and considered it a documented limitation (and used that longjmp magic to fix that).

But I agree, if https://github.com/freemint/freemint/issues/139#issuecomment-576078794 is true, it's really dangerous.

**Comment by czietz** [comment]
> But I agree, if [#139 (comment)](https://github.com/freemint/freemint/issues/139#issuecomment-576078794) is true, it's really dangerous.

It _is_ true. It's easy to construct a program that crashes when not using SuperToUser(). For example:

```
#include <osbind.h>

void foo1(int bar);
void foo2(int bar);
void foo3(int bar);

void crashme(void) {
	long oldssp = Super(0ul);
	foo1(1);
	foo2(2);
	Super(oldssp);
	foo3(3);
}
```
... when compiled with `m68k-atari-mint-gcc -fomit-frame-pointer -O1 -c superbad.c` yields the code below. You can see how the stack for all three calls is cleared only at the end (offset 0x3a). However, the stack is previously reset to the state at the beginning of the function by Super(oldssp) and therefore the program will crash.

```
  0:   48e7 3020       moveml %d2-%d3/%a2,%sp@-
   4:   7000            moveq #0,%d0
   6:   2f00            movel %d0,%sp@-
   8:   3f3c 0020       movew #32,%sp@-
   c:   4e41            trap #1
   e:   5c8f            addql #6,%sp
  10:   2600            movel %d0,%d3
  12:   4878 0001       pea 1
  16:   4eb9 0000 0000  jsr _foo1
  1c:   4878 0002       pea 2
  20:   4eb9 0000 0000  jsr _foo2
  26:   2f03            movel %d3,%sp@-
  28:   3f3c 0020       movew #32,%sp@-
  2c:   4e41            trap #1
  2e:   5c8f            addql #6,%sp
  30:   4878 0003       pea 3
  34:   4eb9 0000 0000  jsr _foo3
  3a:   4fef 000c       lea %sp@(12),%sp
  3e:   4cdf 040c       moveml %sp@+,%d2-%d3/%a2
  42:   4e75            rts
```

**Comment by vinriviere** [comment]
Note that the problem exists even with plain assembler. With the traditional `Super()` binding, it is impossible to access any stack data after going back to user mode. Nonsense.
