### ISSUE TITLE
100% ColdFire distribution

### ISSUE THREAD

**Issue by vinriviere** [freemint/freemint#91]
My long term objective is to get rid of my own FreeMiNT build for the FireBee:
http://vincent.riviere.free.fr/soft/m68k-atari-mint/archives/mint/freemint/

It will be possible when the official FreeMiNT build for ColdFire is 100% ColdFire, and contains as at least as much software than my build.
https://freemint.github.io/

Maybe it is already good enough.
Every binary in the FreeMiNT ColdFire archive needs to be checked to be 100% ColdFire. For example, by testing them on FireBee+EmuTOS.

**Comment by DavidGZ** [comment]
I run my FireBee normally with EmuTOS + MiNT and I get the binaries from the official distributions or compiling them myself when doing some testing, the only thing that is in your distribution that I didn't check is the NFS driver, for the rest from my experience they should be already 100% ColdFire.

**Comment by DavidGZ** [comment]
Yes you're right, but his FreeMiNT package linked above doesn't contain those tools, so the contents of his build are already 100% ColdFire in the official package.

**Comment by th-otto** [comment]
His archive maybe not, because he choosed to only include compatible versions. But the automated builds contain all those tools (in /mint/x-xx-xxx/sysroot/bin mostly). I could not figure out the magic from the build scripts yet, but when you do a local "make all" in the toplevel directory, there is only one version of those tools, as opposed to the kernel/drivers, which are compiled for all flavours.

**Comment by DavidGZ** [comment]
I have done it for some drivers, I can start doing it for the tools too.
This commit can help to understand it:
https://github.com/freemint/freemint/commit/311e51ba1863d04ea8bdcec4f2eac2eb50b1993d#diff-d12fa3081552acc063cff22ab087c278

Mainly you need to create a XXXXDEFS file and Makefile.objs, also modify a bit the already existing Makefile

**Comment by th-otto** [comment]
Yes, basically i know what to do. The question is whether that is necessary. At least it would break the build scripts: https://travis-ci.org/freemint/freemint/jobs/404945271#L5851
There you can see that it is already taken care of. Just not for local builds.

**Comment by mikrosk** [comment]
Yes, Travis builds cheat. :) So if this task is about having an automated local ColdFire builds for the tools directory then sure, this is missing otherwise it is done and publicly available for some time already.

**Comment by DavidGZ** [comment]
From the link you've posted I see that all the tools are already built for the ColdFire in the official package, you're confusing me :-) some posts above you wrote that they were only build for the 000. I know locally not but we were talking about distribution packages.
So we only need to check that they are running without issues natively so Vincent can get rid of his package.

>The question is whether that is necessary. At least it would break the build scripts: https://travis-ci.org/freemint/freemint/jobs/404945271#L5851

I guess the thing to do would be to complete the local build process for the rest of archs and then change the official package build scripts.

**Comment by th-otto** [comment]
> some posts above you wrote that they were only build for the 000

If you build them locally, yes. The automated scripts do much more work by creating dedicated directories, passing CPU=v4e etc.

Personally, i can live with the current situation. I don't have a FireBee, so i don't need CF binaries. But for Vincent it would be difficult to test changes before committing: basically he has do repeat all the magic that is done in the build scripts currently.
OTOH, changing the Makefiles to support such builds out-of-the-box, will be quite some work (there are lots of them).

**Comment by vinriviere** [comment]
> So if this task is about having an automated local ColdFire builds for the tools directory then sure, this is missing

The issue discussed here is to ensure that FreeMiNT is able to distribute itself (with tools) 100% ColdFire (or 68020-60, or anything else) with automated builds, so other people (i.e. me) don't have to make special, unofficial builds to reach that goal. I provided my own FreeMiNT distribution because official FreeMiNT builds were far from that goal. But now, it seems that we are very close... So that task should be finished (if not already finished, I haven't tested the tools).

Here is the rule I have chosen for my own builds:
- Static libraries are built for multiple variants, so the build system (usually cross-compiler) can build any variant of any executable.
- Executables are built for a single variant, and bundled into an archive dedicated to that variant.
So:
- Developers can build software for any variant
- Users have only optimized programs, nothing more

And from what I see of FreeMiNT archives, we are very close to that goal.

**Comment by mfro0** [comment]
To me, this is essentially the same like #12 

As I own a FireBee, a Falcon, a TT and a MiST, I found myself regularily forced to do "special" builds for ColdFire, 030 and plain 68000.

**Comment by vinriviere** [comment]
As a user, I just want to download software ad run it, avoiding unoptimized or incompatible binaries. I don't want to make special builds myself, I just want to download and enjoy. This is what automated builds are supposed to provide. I don't say that everything must be done cleanly right now, I just say that's the goal.

**Comment by mikrosk** [comment]
Guys, just download the new builds and enjoy. :-) I had invested a nontrivial amount of time into that infrastructure so if something isn't working, it's a bug. Personally I don't care about machines anymore, I use one shared folder for my Falcon030/CT2/CT60/Aranym without _one single change_ anywhere. It works out of the box incl. proper drivers (svethlana.xif is run only on CT60, nfstderr.xdd only on Aranym etc). That was the whole point.

I don't remember building my own kernel for a good two years, except the cases when debugging something.

Having a less confusing makefiles is, as @mfro0 has pointed out, addressed in #12.

**Comment by vinriviere** [comment]
@mikrosk We totally agree 🙂
The main point of this issue is:
Ensure that automatically built `freemint-*-col.zip` from https://freemint.github.io/ only contains 100% ColdFire binaries. Concretely, test each binary on FireBee/EmuTOS/FreeMiNT. If it works, that's fine. If not, fix the Makefile or build script. And when everything has been checked, close the issue. Should be simple.
Experience shows that even when it should work, it can't never be assumed that it actually works until really tested.

**Comment by mikrosk** [comment]
@vinriviere if it's only about checking, one can open the travis log and look for CPU flags used: https://travis-ci.org/freemint/freemint/jobs/404945271 :)

I remember @th-otto catching a couple of bugs (-m68020-60 was ignored in some cases) but that should be all fine now. AFAIK, the FireBee guys download exclusively only the official builds and I haven't heard a single complain.

**Comment by vinriviere** [comment]
No, it is not only about checking the CPU flags (even if its the first thing to check). I hit many issues where a few 68000 instructions were hiding inside inline assembly, or rarely used library functions. The only way to be sure is to test on 100% ColdFire OS.

Note that all FireBee guys use FireTOS, which has 680x0 emulation. So if a few 680x0 instructions are still present, it will still work. The only valid test is EmuTOS for ColdFire.

**Comment by mikrosk** [comment]
OK, that's a fair point. Although CPU flags should be passed also to `as` so if there's some incompatibility, we should see it. I agree this needs to be verified.

**Comment by mikrosk** [comment]
This should be resolved by David's work on the tools and by https://github.com/freemint/freemint/commit/36cf2b41b10394e42ce50ccb0035afbc81a851b7. Everything is explicitly built for ColdFire only and packaged into the official archive(s). Until somebody reports something is wrong, closing.
